---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[my_mongo::install_mongo]
      - recipe[my_mongo::generate_mongoid_yml]
    attributes:
